### ISSUE TITLE
1.1.1 Files outside of src

### ISSUE THREAD

**Issue by haydencrain** [kirillDanshin/halogenium#1]
Hi! 

I was just curious if there was a reason that the 1.1.1 files are outside of the src folder.

Many thanks for updating and maintaining the halogen repo! :)

**Comment by kirillDanshin** [comment]
hi! sorry for late answer.

It's distro files built by original build automation. I'm working on rewriting halogenium in es6 and rewriting build script.

thanks for your feedback, glad to see you're happy! :)

**Comment by kirillDanshin** [comment]
@haydencrain ping me, if you have any questions
