### ISSUE TITLE
Moonloader has size 0

### ISSUE THREAD

**Issue by rufman** [kirillDanshin/halogenium#10]
This line https://github.com/kirillDanshin/halogenium/blob/master/src/MoonLoader.jsx#L65 is means that passing a size as a string doesn't work (which is the default value of the prop). I'm not sure if the propType should be changed to just a number, or alternatively to properly support string sizes.

**Comment by kirillDanshin** [comment]
good catch.
will fix this today or feel free to send me PR.
thank you!

**Comment by mfolnovic** [comment]
@kirillDanshin Could you release new version with this fix?
