### ISSUE TITLE
PacmanLoader is broken

### ISSUE THREAD

**Issue by rrsilaya** [kirillDanshin/halogenium#14]
PacmanLoader renders wrong with 5 pacman figures. It does not animate anyway.

**Comment by kirillDanshin** [comment]
did you embed it in container with `display: flex`?

**Comment by rrsilaya** [comment]
Yes. If I'm using other loaders, it's okay.

**Comment by kirillDanshin** [comment]
it may occur in current halogenium version, as a workaround you can try use it in `display: block` container, but I'll fix it ASAP. anyway, PR are also welcome :)
