### ISSUE TITLE
An error occurs when importing the library.

### ISSUE THREAD

**Issue by loconluis** [kirillDanshin/halogenium#21]
I cant use this library, always send an error
```
document is not defined
```

![captura de pantalla 2018-03-21 a la s 12 28 44 p m](https://user-images.githubusercontent.com/12422912/37729737-73e2c0ec-2d03-11e8-8aa7-6e27e506c35e.png)

💀

**Comment by kirillDanshin** [comment]
hi. this library currently doesn't support SSR

**Comment by kirillDanshin** [comment]
fixed
