### ISSUE TITLE
Warning: ClipLoader: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

### ISSUE THREAD

**Issue by navinesh** [kirillDanshin/halogenium#3]

**Comment by kirillDanshin** [comment]
thanks, I'm working on rewriting the lib in es6.

again, thanks for your report.

**Comment by haydencrain** [comment]
@kirillDanshin have you updated any of the files to es6? (e.g. what is your progress so far)
I'm more than happy to help convert them, all I might need is just a completed example as a guide 😃

**Comment by kirillDanshin** [comment]
@haydencrain thanks! really glad to see that :)
now I've done test `prerelease` build script and 6 components. I plan to release full alpha version today or tomorrow.

**Comment by Vishal0203** [comment]
@kirillDanshin waiting for the new release. I've started using halogenium for now, but I'll love to see those console errors go away.

**Comment by joelfsreis** [comment]
@kirillDanshin do you plan to release a fix for this soon?

**Comment by AlexChesters** [comment]
Any progress on getting a release for this soon? Happy to help out if needed.

**Comment by kirillDanshin** [comment]
@navinesh @haydencrain @Vishal0203 @joelfsreis @AlexChesters 2.0.0-rc1 is published

**Comment by kirillDanshin** [comment]
p.s. sorry for late reply

**Comment by dnlsandiego** [comment]
@kirillDanshin Just tried the v2 rc and the errors are still showing up. Is the usage for v2-rc1 the same as the ones shown in the README?

**Comment by kirillDanshin** [comment]
@dnlsandiego yep. I've checked up if errors are still there but after this patch those seems to be fixed

**Comment by kirillDanshin** [comment]
please use just released 2.0.0
