### ISSUE TITLE
Couple new errors from v2.0.0-rc1

### ISSUE THREAD

**Issue by dnlsandiego** [kirillDanshin/halogenium#4]
Hey folks, I just tried the v2.0.0-rc1 and although it fixed the problems from halogen, it seems as though 2 new warnings are popping up.

`warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

`warning.js:36 Warning: getDefaultProps was defined on DotLoader, a plain JavaScript class. This is only supported for classes created using React.createClass. Use a static property to define defaultProps instead.`

I'm open to putting together a PR to fix these warnings.

**Comment by kirillDanshin** [comment]
Sorry for late reply, I'm still sick.
Please send a PR.

**Comment by kirillDanshin** [comment]
please use just released 2.0.0
