### ISSUE TITLE
Module not found: Error: Can't resolve 'halogenium/ClipLoader'

### ISSUE THREAD

**Issue by kongakong** [kirillDanshin/halogenium#5]
I have run 

`npm install halogenium --save`

Then in my code
```

import React, { Component, PropTypes } from 'react';
import Loader from 'halogenium/ClipLoader';

...
return (
      <div className={styles['checking-status-spinner']}>
        <Loader color={color} />
      </div>
)
```

I got this error message:

      Module not found: Error: Can't resolve 'halogenium/ClipLoader' 

Do you have any suggestion?

I am using webpack 2.3.3, react 15.5.2 and babel 6.5.2

**Comment by louisblin** [comment]
I believe the main `README` documentation is out of date if you use the latest version of this repo: ` 2.0.0-rc1`. The library is currently being rewritten in ES6 [#3 (comment)](https://github.com/kirillDanshin/halogenium/issues/3#issuecomment-295200098), changing the import line from:
```
import Loader from 'halogenium/ClipLoader';
```
to:
```
import { ClipLoader } from 'halogenium';
```

However it's not perfectly working yet, see #4 .

For the time being, I'd downgrade to `1.1.1` (`npm install --save halogenium@1.1.1`) which should let you use the library, although you'll still get some React >= 15.5 warnings - see #3

**Comment by kongakong** [comment]
Thanks! It fixed my problem.
