### ISSUE TITLE
getDefaultProps was defined on PulseLoader, a plain JavaScript class.

### ISSUE THREAD

**Issue by yipsang** [kirillDanshin/halogenium#8]
Got this warning when importing PulseLoader from halogenium

`getDefaultProps was defined on PulseLoader, a plain JavaScript class. This is only supported for classes created using React.createClass. Use a static property to define defaultProps instead.`

**Comment by kirillDanshin** [comment]
Hi!

What version do you use?

**Comment by yipsang** [comment]
hi @kirillDanshin 
I am using 2.0.1

**Comment by kirillDanshin** [comment]
sorry for the delay

please update to 2.1.0 and ping me if it fixed or not

**Comment by yipsang** [comment]
@kirillDanshin 
Thanks, the warning is gone after updating to 2.1.0. But FYI, 2.0.1 is the default version I've got via npm install halogenium --save

**Comment by kirillDanshin** [comment]
@yipsang  cool!
I released 2.1.0 to fix your issue, so now npm i -S halogenium will install @2.1.0
Closing the issue. Thanks for reporting
